import React from 'react';
import { Link } from 'react-router-dom';
import { Mail, Users, Clock, TrendingUp, Target, BarChart3, CheckCircle, Zap } from 'lucide-react';

const EmailMarketing: React.FC = () => {
  const services = [
    {
      icon: Users,
      title: 'Smart Segmentation & Personalization',
      description: 'AI-driven dynamic customer segments that automatically update based on behavior, preferences, and engagement patterns.'
    },
    {
      icon: Zap,
      title: 'Behavioral Trigger Automation',
      description: 'Intelligent email sequences that respond to specific customer actions with perfectly timed, relevant messages.'
    },
    {
      icon: Clock,
      title: 'Predictive Send Time Optimization',
      description: 'AI analyzes individual recipient patterns to determine the optimal send time for maximum engagement.'
    },
    {
      icon: Target,
      title: 'Lead Scoring & Qualification',
      description: 'AI identifies your hottest prospects automatically, prioritizing follow-up and sales efforts for maximum conversion.'
    },
    {
      icon: TrendingUp,
      title: 'Customer Journey Mapping',
      description: 'Precision-guided sales funnel optimization that moves prospects through your buying process intelligently.'
    },
    {
      icon: BarChart3,
      title: 'Revenue Attribution Tracking',
      description: 'Track exact revenue generated by each email campaign, sequence, and customer touchpoint with AI-powered analytics.'
    }
  ];

  const results = [
    { metric: '340%', label: 'Higher Engagement Rates' },
    { metric: '24/7', label: 'Automated Lead Nurturing' },
    { metric: '95%', label: 'Email Deliverability Rate' }
  ];

  const automationExamples = [
    {
      trigger: 'New Lead Capture',
      sequence: 'Welcome series with value-driven content, product education, and gentle sales progression over 14 days.'
    },
    {
      trigger: 'Abandoned Cart',
      sequence: 'Smart recovery sequence with personalized product recommendations and limited-time incentives.'
    },
    {
      trigger: 'Purchase Completion',
      sequence: 'Onboarding flow, usage tips, upsell opportunities, and review requests based on customer lifecycle.'
    },
    {
      trigger: 'Website Behavior',
      sequence: 'Content-specific follow-up based on pages visited, time spent, and interest indicators.'
    },
    {
      trigger: 'Re-engagement',
      sequence: 'Win-back campaigns for inactive subscribers with personalized offers and survey requests.'
    }
  ];

  const features = [
    'Advanced A/B testing with statistical significance',
    'Dynamic content personalization for every recipient',
    'Automated list cleaning and deliverability optimization',
    'Integration with CRM and sales tools',
    'Real-time campaign performance dashboards',
    'Compliance with CAN-SPAM and GDPR regulations'
  ];

  return (
    <div>
      {/* Hero Section */}
      <section className="bg-forest-green text-white section-padding">
        <div className="container">
          <div className="max-w-4xl mx-auto text-center">
            <h1 className="text-5xl font-bold mb-6">Intelligent Email Marketing</h1>
            <p className="text-xl text-gray-200 mb-8">
              Transform your email marketing from manual broadcasts to intelligent, automated conversations 
              that nurture leads and drive revenue 24/7. AI-powered personalization at scale.
            </p>
            <Link to="/contact" className="btn-primary bg-white text-forest-green hover:bg-gray-100 text-lg px-8 py-4">
              Upgrade Your Email Marketing
            </Link>
          </div>
        </div>
      </section>

      {/* Results Section */}
      <section className="bg-light-gray section-padding">
        <div className="container">
          <div className="text-center mb-12">
            <h2 className="text-3xl font-bold mb-4">Intelligent Email Marketing Results</h2>
            <p className="text-xl text-text-secondary">Real improvements our clients have achieved</p>
          </div>
          
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {results.map((result, index) => (
              <div key={index} className="text-center">
                <div className="text-5xl font-bold text-forest-green mb-2">{result.metric}</div>
                <div className="text-lg font-medium text-text-secondary">{result.label}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Services Grid */}
      <section className="section-padding">
        <div className="container">
          <div className="text-center mb-12">
            <h2 className="text-4xl font-bold mb-4">Complete Intelligent Email Solutions</h2>
            <p className="text-xl text-text-secondary max-w-2xl mx-auto">
              From smart segmentation to revenue attribution, we create email systems that work like having 
              a dedicated marketing team running 24/7.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 mb-12">
            {services.map((service, index) => {
              const IconComponent = service.icon;
              return (
                <div key={index} className="card group">
                  <div className="bg-light-green p-3 rounded-lg w-fit mb-4 group-hover:bg-forest-green group-hover:text-white transition-colors">
                    <IconComponent className="h-6 w-6" />
                  </div>
                  <h3 className="text-xl font-semibold mb-3">{service.title}</h3>
                  <p className="text-text-secondary">{service.description}</p>
                </div>
              );
            })}
          </div>

          <div className="text-center">
            <Link to="/contact" className="btn-primary text-lg px-8 py-4">
              Learn More About This Solution
            </Link>
          </div>
        </div>
      </section>

      {/* Automation Examples */}
      <section className="bg-light-green section-padding">
        <div className="container">
          <div className="text-center mb-12">
            <h2 className="text-4xl font-bold mb-4">Smart Email Automation Sequences</h2>
            <p className="text-xl text-text-secondary">
              Pre-built, proven email sequences that activate based on customer behavior and lifecycle stage
            </p>
          </div>

          <div className="max-w-4xl mx-auto space-y-6">
            {automationExamples.map((example, index) => (
              <div key={index} className="card">
                <div className="flex items-start space-x-6">
                  <div className="bg-forest-green text-white p-3 rounded-lg">
                    <Mail className="h-6 w-6" />
                  </div>
                  <div className="flex-1">
                    <h3 className="text-xl font-semibold mb-2 text-forest-green">{example.trigger}</h3>
                    <p className="text-text-secondary">{example.sequence}</p>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="section-padding">
        <div className="container">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
            <div>
              <h2 className="text-4xl font-bold mb-6">Why Tulsa Businesses Choose Our Email Marketing</h2>
              <p className="text-xl text-text-secondary mb-8">
                Stop sending generic mass emails that get ignored. Our AI-powered system creates personalized 
                conversations that build relationships and drive revenue.
              </p>
              
              <div className="space-y-4">
                {features.map((feature, index) => (
                  <div key={index} className="flex items-center space-x-3">
                    <CheckCircle className="h-5 w-5 text-forest-green flex-shrink-0" />
                    <span className="text-text-primary">{feature}</span>
                  </div>
                ))}
              </div>
            </div>

            <div className="card">
              <h3 className="text-2xl font-bold mb-4 text-center">Ready to Automate Your Email Marketing?</h3>
              <p className="text-text-secondary text-center mb-6">
                Get intelligent email sequences that nurture leads and drive sales automatically.
              </p>
              <div className="space-y-4">
                <div className="flex items-center space-x-3 text-sm">
                  <CheckCircle className="h-4 w-4 text-forest-green" />
                  <span>Complete email automation setup</span>
                </div>
                <div className="flex items-center space-x-3 text-sm">
                  <CheckCircle className="h-4 w-4 text-forest-green" />
                  <span>Pre-written email sequences</span>
                </div>
                <div className="flex items-center space-x-3 text-sm">
                  <CheckCircle className="h-4 w-4 text-forest-green" />
                  <span>AI-powered personalization</span>
                </div>
                <div className="flex items-center space-x-3 text-sm">
                  <CheckCircle className="h-4 w-4 text-forest-green" />
                  <span>Revenue tracking and optimization</span>
                </div>
                <Link to="/contact" className="btn-primary w-full text-center py-3">
                  Get Intelligent Email Marketing
                </Link>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Customer Journey Visualization */}
      <section className="bg-light-gray section-padding">
        <div className="container">
          <div className="max-w-4xl mx-auto">
            <div className="text-center mb-12">
              <h2 className="text-4xl font-bold mb-4">Intelligent Customer Journey</h2>
              <p className="text-xl text-text-secondary">
                See how AI guides prospects through your sales funnel automatically
              </p>
            </div>

            <div className="card">
              <div className="space-y-8">
                <div className="flex items-center space-x-4">
                  <div className="bg-forest-green text-white w-12 h-12 rounded-full flex items-center justify-center font-bold">1</div>
                  <div className="flex-1">
                    <h3 className="font-semibold mb-1">Lead Capture</h3>
                    <p className="text-sm text-text-secondary">Visitor subscribes → Immediate welcome email with valuable content</p>
                  </div>
                  <div className="text-forest-green font-bold">Day 0</div>
                </div>

                <div className="flex items-center space-x-4">
                  <div className="bg-forest-green text-white w-12 h-12 rounded-full flex items-center justify-center font-bold">2</div>
                  <div className="flex-1">
                    <h3 className="font-semibold mb-1">Nurture Sequence</h3>
                    <p className="text-sm text-text-secondary">Educational content, case studies, and social proof delivered over 7 days</p>
                  </div>
                  <div className="text-forest-green font-bold">Days 1-7</div>
                </div>

                <div className="flex items-center space-x-4">
                  <div className="bg-forest-green text-white w-12 h-12 rounded-full flex items-center justify-center font-bold">3</div>
                  <div className="flex-1">
                    <h3 className="font-semibold mb-1">Engagement Scoring</h3>
                    <p className="text-sm text-text-secondary">AI tracks opens, clicks, and website behavior to identify hot prospects</p>
                  </div>
                  <div className="text-forest-green font-bold">Ongoing</div>
                </div>

                <div className="flex items-center space-x-4">
                  <div className="bg-forest-green text-white w-12 h-12 rounded-full flex items-center justify-center font-bold">4</div>
                  <div className="flex-1">
                    <h3 className="font-semibold mb-1">Sales Activation</h3>
                    <p className="text-sm text-text-secondary">High-scoring leads get priority follow-up and targeted offers</p>
                  </div>
                  <div className="text-forest-green font-bold">Days 8-14</div>
                </div>

                <div className="flex items-center space-x-4">
                  <div className="bg-forest-green text-white w-12 h-12 rounded-full flex items-center justify-center font-bold">5</div>
                  <div className="flex-1">
                    <h3 className="font-semibold mb-1">Conversion & Retention</h3>
                    <p className="text-sm text-text-secondary">Post-purchase onboarding, upsells, and long-term relationship building</p>
                  </div>
                  <div className="text-forest-green font-bold">Post-Sale</div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Case Study */}
      <section className="section-padding">
        <div className="container">
          <div className="max-w-4xl mx-auto">
            <div className="text-center mb-12">
              <h2 className="text-4xl font-bold mb-4">Email Marketing Success Story</h2>
              <p className="text-xl text-text-secondary">
                How a Tulsa professional services firm increased revenue 240% with intelligent email automation
              </p>
            </div>

            <div className="card">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                <div>
                  <h3 className="text-2xl font-semibold mb-4">The Challenge</h3>
                  <p className="text-text-secondary mb-6">
                    A growing consulting firm was sending weekly newsletters to their list but seeing poor engagement 
                    and minimal revenue attribution. Leads weren't being nurtured effectively.
                  </p>
                  
                  <h3 className="text-2xl font-semibold mb-4">Our Solution</h3>
                  <p className="text-text-secondary">
                    We implemented behavioral trigger automation, smart segmentation based on service interests, 
                    and personalized nurture sequences with AI-optimized send times.
                  </p>
                </div>
                
                <div>
                  <h3 className="text-2xl font-semibold mb-4">Results</h3>
                  <div className="space-y-4">
                    <div className="flex items-center justify-between p-3 bg-light-green rounded-lg">
                      <span>Open Rates</span>
                      <span className="font-bold text-forest-green">+180%</span>
                    </div>
                    <div className="flex items-center justify-between p-3 bg-light-green rounded-lg">
                      <span>Click-Through Rates</span>
                      <span className="font-bold text-forest-green">+340%</span>
                    </div>
                    <div className="flex items-center justify-between p-3 bg-light-green rounded-lg">
                      <span>Lead-to-Customer Rate</span>
                      <span className="font-bold text-forest-green">+150%</span>
                    </div>
                    <div className="flex items-center justify-between p-3 bg-light-green rounded-lg">
                      <span>Email-Attributed Revenue</span>
                      <span className="font-bold text-forest-green">+240%</span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="bg-forest-green text-white section-padding">
        <div className="container text-center">
          <h2 className="text-4xl font-bold mb-4">Ready to Transform Your Email Marketing?</h2>
          <p className="text-xl text-gray-200 max-w-2xl mx-auto mb-8">
            Stop sending emails into the void. Start building relationships and driving revenue with 
            intelligent email marketing that works 24/7.
          </p>
          <Link to="/contact" className="btn-primary bg-white text-forest-green hover:bg-gray-100 text-lg px-8 py-4">
            Upgrade Your Email Marketing
          </Link>
        </div>
      </section>
    </div>
  );
};

export default EmailMarketing;